## 14.4 more about exceptions

- multiply catch blocks

```c++
float ratio(float a, float b){
    if(a < 0) throw 1;
    if(b < 0) throw 2;
    if(fabs(a + b) < FLT_EPSILON) throw "Error...";
    return (a - b) / (a + b);
}

// try exceptions

try {
    float z = radio(x, y);
} catch(const char *msg){
    ...
} catch(int e_code){
    ...
}

```

### 如果有很多异常，不方便穷举，怎么办？

```c++
// catch all kinds of exceptions
try {
    ...
} catch(...){ // 这里用 ...
    
}
```

### Exceptions and Inheritance

```c++
// 抛出一个子类的异常，catch 父类可以捕获到，后面的 catch子类 就不会走了
try {
    throw Derived();
} catch (const Base &base) {
    ...
} catch (const Derived &derived) {
    ... // never reach here
}
```

### `std::exception`

- is a class which can be a base class to any exception
- 函数 ``std::exception::what()`` can be overridden to return a C-style string message

#### exception 的子类

```c++
namespace std {
    class logic_error;
    class domain_error;
    class invalid_error;
    class length_error;
    class out_of_range;
    class runtime_error;
    class range_error;
    class overflow_error;
    class underflow_error;
}
```

### noexcept

- 指定函数不会抛出任何异常
```c++
void foo() noexcept;
```